apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "craftista.labels" (dict "root" . "name" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" (dict "root" . "name" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "craftista.labels" (dict "root" . "name" "frontend") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000          # пользователь node в образе
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: {{ include "craftista.image" (dict "root" . "svc" .Values.frontend) | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet: { path: /, port: http }
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "craftista.labels" (dict "root" . "name" "frontend") | nindent 4 }}
spec:
  selector:
    {{- include "craftista.selectorLabels" (dict "root" . "name" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
